/*
 * QuecTelM66.h
 *
 *  Created on: Apr 17, 2018
 *      Author: HP
 */

#ifndef BSP_COMPONENTS_QUECTELM66_QUECTELM66_H_
#define BSP_COMPONENTS_QUECTELM66_QUECTELM66_H_


#include <Parser/AtCommandParser.h>

#define USE_GENERAL_COMMAND
#define USE_INTERFACE_CONTROL_COMMAND
#define USE_STATUS_CONTROL_COMMAND
#define USE_SIM_RELATED_COMMAND
#define USE_NETWORK_SERVICE_COMMAND
#define USE_CALL_RELATED_COMMAND
#define USE_SMS_COMMAND
#define USE_PHONEBOOK_COMMAND
#define USE_GPRS_COMMAND
#define USE_TCPIP_COMMAND
#define USE_SUPPLEMENTARY_COMMAND
#define USE_AUDIO_COMMAND
#define USE_HARDWARE_RELATED_COMMAND
#define USE_OTHER_COMMAND

#define GENERAL_COMMAND_COUNT				23
#define INTERFACE_CONTROL_COMMAND_COUNT		7
#define STATUS_CONTROL_COMMAND_COUNT		13
#define SIM_RELATED_COMMAND_COUNT			11
#define NETWORK_SERVICE_COMMAND_COUNT		9
#define CALL_RELATED_COMMAND_COUNT			22
#define SMS_COMMAND_COUNT					20
#define PHONEBOOK_COMMAND_COUNT				5
#define GPRS_COMMAND_COUNT					12
#define TCPIP_COMMAND_COUNT					34
#define SUPPLEMENTARY_COMMAND_COUNT			11
#define AUDIO_COMMAND_COUNT					18
#define HARDWARE_RELATED_COMMAND_COUNT		5
#define OTHER_COMMAND_COUNT					8




#endif /* BSP_COMPONENTS_QUECTELM66_QUECTELM66_H_ */
